sudo: false

language: python
python:
  - 2.7

virtualenv:
    system_site_packages: true

addons:
  apt:
    packages:
    #- python-numpy
    #- python-scipy
    - python-qt4
    #- python-matplotlib
    #- root-system  #don't install ROOT yet
    
install:
  - python -c "import sys; print sys.path"
  - pip install scipy
  - pip install numpy
  - pip install matplotlib
  - pip show matplotlib
  - pip install --upgrade pip
  - pip install --upgrade iminuit
  - python -c "import sys; print sys.path"
  - python -c "import numpy"
  - python -c "import scipy"
  - python -c "import matplotlib"
  - pip install -e .

script:
  - |
    cd examples/example1_model_comparison
    python example1_model_comparison.py
