sudo: required
dist: trusty
language: python
python:
  - 2.7

virtualenv:
    system_site_packages: true

before_install:
  - |
    # Travis tools
    source ci/travis/travis_tools.sh
    virtualenv --python=python myenv
    source myenv/bin/activate

install:
  - pip install --upgrade pip
  - sudo apt-get -qq install python-numpy
  - sudo apt-get -qq install python-scipy
  - sudo apt-get -qq install python-qt4
  - sudo apt-get -qq install python-matplotlib
  - sudo apt-get -qq install root-system
  - pip install --upgrade iminuit
  - pip install -e .

script:
  - |
    cd examples/example1_model_comparison
    python example1_model_comparison.py
