sudo: required
dist: trusty
language: python
python:
  - 2.7

before_install:
  - |
    # Travis tools
    source ci/travis/travis_tools.sh
    virtualenv --python=python myenv
    source myenv/bin/activate

install:
  - pip install --upgrade pip
  - sudo apt-get -y install python-numpy
  - sudo apt-get -y install python-scipy
  - sudo apt-get -y install python-qt4
  - sudo apt-get -y install python-matplotlib
  - sudo apt-get -y install root-system
  - pip install --upgrade iminuit
  - sudo python setup.py install

script:
  - |
    cd examples/example1_model_comparison
    python example1_model_comparison.py
