sudo: false

language: python
python:
  - 2.7

addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - python-qt4
    - python-matplotlib
    - root-system
    
install:
  - pip install --upgrade pip
  - pip install --upgrade iminuit
  - pip install -e .

script:
  - |
    cd examples/example1_model_comparison
    python example1_model_comparison.py
